baseURL = "https:/flygare.me/"
languageCode = "en-us"
title = "Robin Flygare | Software developer"
theme = "introduction"

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    #fadeIn                       = false                      # Turn on/off the fade-in effect
    #fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    email                        = "robin@flygare.me"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/
    [[params.social]]
        url   = "https://github.com/flygare"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://linkedin.com/in/robinflygare"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:robin@flygare.me"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fas"
